services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=montbank'
      - 'POSTGRES_PASSWORD=montpass'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  user:
    build: ./ms-user
    container_name: user
    depends_on:
     - postgres
    ports:
      - '8081:8080'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/montbank'
      SPRING_DATASOURCE_USERNAME: 'postgres'
      SPRING_DATASOURCE_PASSWORD: 'montpass'
  #rabbitmq:
    #image: 'rabbitmq:latest'
    #environment:
     # - 'RABBITMQ_DEFAULT_PASS=secret'
     # - 'RABBITMQ_DEFAULT_USER=myuser'
   # ports:
     # - '5672'



volumes:
  postgres_data: