services:

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    expose:
      - '5672'
    ports:
      - '15672:15672'
    networks:
      - backend-network

  postgres:
    image: 'postgres:15-alpine'
    container_name: postgres
    environment:
      - POSTGRES_DB=montbank
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=montpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - '5432'
    networks:
      - backend-network

  user:
    build: ./ms-user
    container_name: user
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/montbank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: montpass
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    expose:
      - '8082'
    networks:
      - backend-network

  transaction:
    build: ./ms-transaction
    container_name: transaction
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/montbank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: montpass
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    expose:
      - '8083'
    networks:
      - backend-network

  cards:
    build: ./ms-cards
    container_name: cards
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/montbank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: montpass
    expose:
      - '8084'
    networks:
      - backend-network

  email:
    build: ./ms-email
    container_name: email
    depends_on:
      - rabbitmq
      - user
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    expose:
      - '8085'
    networks:
      - backend-network

  gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - user
      - transaction
      - cards
    ports:
      - '8081:8081'
    networks:
      - backend-network

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - gateway
    ports:
      - '8080:8080'
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge
