services:

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      - '5672:5672'
      - '15672:15672'

  postgres:
    image: 'postgres:15-alpine'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=montbank'
      - 'POSTGRES_PASSWORD=montpass'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  user:
    build: ./ms-user
    container_name: user
    depends_on:
     - postgres
     - rabbitmq
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/montbank'
      SPRING_DATASOURCE_USERNAME: 'postgres'
      SPRING_DATASOURCE_PASSWORD: 'montpass'
      SPRING_RABBITMQ_HOST: 'rabbitmq'
      SPRING_RABBITMQ_PORT: '5672'
      SPRING_RABBITMQ_USERNAME: 'guest'
      SPRING_RABBITMQ_PASSWORD: 'guest'

  transaction:
    build: ./ms-transaction
    container_name: transaction
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - '8081:8080'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/montbank'
      SPRING_DATASOURCE_USERNAME: 'postgres'
      SPRING_DATASOURCE_PASSWORD: 'montpass'
      SPRING_RABBITMQ_HOST: 'rabbitmq'
      SPRING_RABBITMQ_PORT: '5672'
      SPRING_RABBITMQ_USERNAME: 'guest'
      SPRING_RABBITMQ_PASSWORD: 'guest'

volumes:
  postgres_data: