server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://user:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1


        - id: transaction
          uri: http://transaction:8082
          predicates:
            - Path=/api/transactions/**
          filters:
            - StripPrefix=1


        - id: cards
          uri: http://cards:8083
          predicates:
            - Path=/api/cards/**
          filters:
            - StripPrefix=1

